#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
   path: /managment/login
   controller: App\Controller\SecurityController::login

app_logout:
   path: /managment/logout
   controller: App\Controller\SecurityController::logout